/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceGraphique;

/**
 *
 * @author idruote
 */
public class FicheRecette extends javax.swing.JFrame {

    private String nom;
	private String instruction;
	private String dureeRecette;
	/**
     * Creates new form FicheRecette
     */
    public FicheRecette() {
        initComponents();
    }

    public FicheRecette(String nom, String duree, String instruction) {
    	this.nom =nom;
        this.dureeRecette = duree;
        this.instruction = instruction;
        initComponents();
        this.addWindowListener(new FermetureFenetre());	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageFicheRecette = new javax.swing.JPanel();
        titreNomRecette = new javax.swing.JLabel();
        choixRecette = new javax.swing.JTextField();
        actualiserRecetteButton = new javax.swing.JButton();
        titreFicheRecette = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableIngredients = new javax.swing.JTable();
        nomRecette = new javax.swing.JLabel();
        Qte = new javax.swing.JLabel();
        listeIngredientsRecette = new javax.swing.JLabel();
        ModifierAlimButton = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();
        afficheInstructions = new javax.swing.JTextField();
        titreDuree = new javax.swing.JLabel();
        duree = new javax.swing.JLabel();
        Menu3 = new javax.swing.JPanel();
        MenuText = new javax.swing.JLabel();
        StockButton3 = new javax.swing.JButton();
        RecetteButton3 = new javax.swing.JButton();
        ListButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  
        setMaximumSize(new java.awt.Dimension(1020, 768));
        setMinimumSize(new java.awt.Dimension(1020, 768));
        setResizable(false);
        setPreferredSize(new java.awt.Dimension(1020, 768));
        setLocationRelativeTo(null);

        pageFicheRecette.setBackground(new java.awt.Color(255, 204, 204));

        titreNomRecette.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titreNomRecette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreNomRecette.setText("Nom Recette :");

        choixRecette.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        choixRecette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixRecetteActionPerformed(evt);
            }
        });

        actualiserRecetteButton.setText("Actualiser");
        actualiserRecetteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserRecetteButtonActionPerformed(evt);
            }
        });

        titreFicheRecette.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        titreFicheRecette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreFicheRecette.setText("Fiche Recette");

        TableIngredients.setModel(Main.controller.afficherIngredientRecette(nom));
            
        jScrollPane1.setViewportView(TableIngredients);

        nomRecette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomRecette.setText(nom);

        Qte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        listeIngredientsRecette.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        listeIngredientsRecette.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listeIngredientsRecette.setText("Liste des ingrédients :");

        ModifierAlimButton.setText("Supprimer Quantite");
        ModifierAlimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierAlimButtonActionPerformed(evt);
            }
        });

        instructions.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        instructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions.setText("Instructions : ");

        afficheInstructions.setText("Ici s'affichera les étapes à suivre pour réussir votre recette.");
        afficheInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficheInstructionsActionPerformed(evt);
            }
        });

        titreDuree.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titreDuree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreDuree.setText("Durée :");

        duree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duree.setText(dureeRecette);

        javax.swing.GroupLayout pageFicheRecetteLayout = new javax.swing.GroupLayout(pageFicheRecette);
        pageFicheRecette.setLayout(pageFicheRecetteLayout);
        pageFicheRecetteLayout.setHorizontalGroup(
            pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                        .addComponent(titreFicheRecette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageFicheRecetteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageFicheRecetteLayout.createSequentialGroup()
                                .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pageFicheRecetteLayout.createSequentialGroup()
                                        .addComponent(titreNomRecette)
                                        .addGap(94, 94, 94)
                                        .addComponent(nomRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pageFicheRecetteLayout.createSequentialGroup()
                                        .addComponent(titreDuree)
                                        .addGap(180, 180, 180)
                                        .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                                                .addComponent(listeIngredientsRecette)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                                                .addComponent(choixRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)))
                                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(actualiserRecetteButton)
                                            .addComponent(Qte, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(352, 352, 352))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageFicheRecetteLayout.createSequentialGroup()
                                .addComponent(ModifierAlimButton)
                                .addGap(33, 33, 33))))
                    .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                        .addComponent(instructions)
                        .addGap(32, 32, 32)
                        .addComponent(afficheInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pageFicheRecetteLayout.setVerticalGroup(
            pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreFicheRecette)
                .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualiserRecetteButton)
                            .addComponent(choixRecette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titreNomRecette)
                            .addComponent(nomRecette))
                        .addGap(18, 18, 18)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Qte)
                                .addComponent(listeIngredientsRecette))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titreDuree)
                            .addComponent(duree))
                        .addGap(31, 31, 31)
                        .addGroup(pageFicheRecetteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instructions)
                            .addComponent(afficheInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pageFicheRecetteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ModifierAlimButton)))
                .addGap(82, 82, 82))
        );

        Menu3.setBackground(new java.awt.Color(153, 204, 255));
        Menu3.setForeground(new java.awt.Color(51, 204, 255));

        MenuText.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        MenuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuText.setText("MENU");
        MenuText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTextMouseClicked(evt);
            }
        });

        StockButton3.setBackground(new java.awt.Color(153, 204, 255));
        StockButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        StockButton3.setText("Stock");
        StockButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockButton3MouseEntered(evt);
            }
        });
        StockButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockButton3ActionPerformed(evt);
            }
        });

        RecetteButton3.setBackground(new java.awt.Color(153, 204, 255));
        RecetteButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        RecetteButton3.setText("Recette");
        RecetteButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecetteButton3MouseClicked(evt);
            }
        });
        RecetteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecetteButton3ActionPerformed(evt);
            }
        });

        ListButton3.setBackground(new java.awt.Color(153, 204, 255));
        ListButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ListButton3.setText("Liste");
        ListButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListButton3MouseClicked(evt);
            }
        });
        ListButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu3Layout = new javax.swing.GroupLayout(Menu3);
        Menu3.setLayout(Menu3Layout);
        Menu3Layout.setHorizontalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RecetteButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(StockButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Menu3Layout.setVerticalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuText)
                .addGap(18, 18, 18)
                .addComponent(StockButton3)
                .addGap(18, 18, 18)
                .addComponent(RecetteButton3)
                .addGap(18, 18, 18)
                .addComponent(ListButton3)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageFicheRecette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pageFicheRecette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTextMouseClicked
        Main.controller.changerPage("accueil", null, null, null);
        this.dispose();
    }//GEN-LAST:event_MenuTextMouseClicked

    private void StockButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockButton3MouseClicked
        //SUP
    }//GEN-LAST:event_StockButton3MouseClicked

    private void StockButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockButton3MouseEntered
        //SUP
    }//GEN-LAST:event_StockButton3MouseEntered

    private void StockButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockButton3ActionPerformed
        Main.controller.changerPage("menuStock", null, null, null);
        this.dispose();
    }//GEN-LAST:event_StockButton3ActionPerformed

    private void RecetteButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecetteButton3MouseClicked
        //SUP
    }//GEN-LAST:event_RecetteButton3MouseClicked

    private void RecetteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecetteButton3ActionPerformed
        Main.controller.changerPage("menuRecette", null, null, null);
        this.dispose();
    }//GEN-LAST:event_RecetteButton3ActionPerformed

    private void ListButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListButton3MouseClicked
        //SUP
    }//GEN-LAST:event_ListButton3MouseClicked

    private void ListButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButton3ActionPerformed
        Main.controller.changerPage("menuListe", null, null, null);
        this.dispose();
    }//GEN-LAST:event_ListButton3ActionPerformed

    private void afficheInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficheInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afficheInstructionsActionPerformed

    private void ModifierAlimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierAlimButtonActionPerformed
        Main.controller.changerPage("modifierUnAliment", null, null, null);
        this.dispose();
    }//GEN-LAST:event_ModifierAlimButtonActionPerformed

    private void actualiserRecetteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserRecetteButtonActionPerformed
        String ac = choixRecette.getText();
        String[] infoRecette = Main.controller.afficherFicheRecette(ac);
        
        nomRecette.setText(infoRecette[0]);
        duree.setText(infoRecette[1]);
        instructions.setText(infoRecette[2]);
        TableIngredients.setModel(Main.controller.afficherIngredientRecette(ac));
        
        

    }



 
        
    //GEN-LAST:event_actualiserRecetteButtonActionPerformed

    private void choixRecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixRecetteActionPerformed
        //SUP
    }//GEN-LAST:event_choixRecetteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheRecette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListButton3;
    private javax.swing.JPanel Menu3;
    private javax.swing.JLabel MenuText;
    private javax.swing.JButton ModifierAlimButton;
    private javax.swing.JLabel Qte;
    private javax.swing.JButton RecetteButton3;
    private javax.swing.JButton StockButton3;
    private javax.swing.JTable TableIngredients;
    private javax.swing.JButton actualiserRecetteButton;
    private javax.swing.JTextField afficheInstructions;
    private javax.swing.JTextField choixRecette;
    private javax.swing.JLabel duree;
    private javax.swing.JLabel instructions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listeIngredientsRecette;
    private javax.swing.JLabel nomRecette;
    private javax.swing.JPanel pageFicheRecette;
    private javax.swing.JLabel titreDuree;
    private javax.swing.JLabel titreFicheRecette;
    private javax.swing.JLabel titreNomRecette;
    // End of variables declaration//GEN-END:variables
}
