/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceGraphique;

import java.awt.Component;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author julesa
 */
public class MenuListe extends JFrame {
    private JButton suprAlimentListeButton;
	

	private JTextField choixQuantiteeListe;
	private JLabel titreAjoutQuantiteeListe;


	private DefaultTableModel tableListeModel;
	

	/**
     * Creates new form MenuListe
     */
    public MenuListe(DefaultTableModel tableListeModel) {
        this.tableListeModel =tableListeModel;
        this.addWindowListener(new FermetureFenetre());

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu3 = new javax.swing.JPanel();
        titreMenu3 = new javax.swing.JLabel();
        StockButton3 = new javax.swing.JButton();
        RecetteButton3 = new javax.swing.JButton();
        ListButton3 = new javax.swing.JButton();
        pageMenuListe = new javax.swing.JPanel();
        titreMenuListe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListe = new javax.swing.JTable();
        ajoutRecetteListe = new javax.swing.JPanel();
        titreAjoutRecetteListe = new javax.swing.JLabel();
        choixRecetteListe = new javax.swing.JTextField();
        ajoutRecetteListeButton = new javax.swing.JButton();
        ajoutAlimentListe = new javax.swing.JPanel();
        titreAjoutAlimentListe = new javax.swing.JLabel();
        choixAlimentListe = new javax.swing.JTextField();
        suprAlimentListeButton = new javax.swing.JButton();
        choixQuantiteeListe = new javax.swing.JTextField();
        ajoutAlimentListeButton = new javax.swing.JButton();
        titreAjoutQuantiteeListe = new javax.swing.JLabel();
        imprimerListeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1020, 768));
        setMinimumSize(new java.awt.Dimension(1020, 768));
        setPreferredSize(new java.awt.Dimension(1020, 768));
        setSize(new java.awt.Dimension(1020, 768));
        setLocationRelativeTo(null);  
        setResizable(false);

        menu3.setBackground(new java.awt.Color(153, 204, 255));
        menu3.setForeground(new java.awt.Color(51, 204, 255));

        titreMenu3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titreMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreMenu3.setText("MENU");
        titreMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titreMenu3MouseClicked(evt);
            }
        });

        StockButton3.setBackground(new java.awt.Color(153, 204, 255));
        StockButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        StockButton3.setText("Stock");
        StockButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockButton3MouseEntered(evt);
            }
        });
        StockButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockButton3ActionPerformed(evt);
            }
        });

        RecetteButton3.setBackground(new java.awt.Color(153, 204, 255));
        RecetteButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        RecetteButton3.setText("Recette");
        RecetteButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecetteButton3MouseClicked(evt);
            }
        });
        RecetteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecetteButton3ActionPerformed(evt);
            }
        });

        ListButton3.setBackground(new java.awt.Color(153, 204, 255));
        ListButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ListButton3.setText("Liste");
        ListButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListButton3MouseClicked(evt);
            }
        });
        ListButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titreMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RecetteButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StockButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreMenu3)
                .addGap(18, 18, 18)
                .addComponent(StockButton3)
                .addGap(18, 18, 18)
                .addComponent(RecetteButton3)
                .addGap(18, 18, 18)
                .addComponent(ListButton3)
                .addContainerGap(642, Short.MAX_VALUE))
        );

        pageMenuListe.setBackground(new java.awt.Color(255, 204, 204));

        titreMenuListe.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        titreMenuListe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreMenuListe.setText("Listes de course");

        tableListe.setModel(tableListeModel);

        jScrollPane1.setViewportView(tableListe);

        ajoutRecetteListe.setBackground(new java.awt.Color(153, 204, 255));

        titreAjoutRecetteListe.setText("Ajouter une recette :");

        ajoutRecetteListeButton.setText("Ajouter");
        

        javax.swing.GroupLayout ajoutRecetteListeLayout = new javax.swing.GroupLayout(ajoutRecetteListe);
        ajoutRecetteListe.setLayout(ajoutRecetteListeLayout);
        ajoutRecetteListeLayout.setHorizontalGroup(
            ajoutRecetteListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutRecetteListeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreAjoutRecetteListe)
                .addGap(18, 18, 18)
                .addComponent(choixRecetteListe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajoutRecetteListeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ajoutRecetteListeLayout.setVerticalGroup(
            ajoutRecetteListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutRecetteListeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutRecetteListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixRecetteListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutRecetteListeButton)
                    .addComponent(titreAjoutRecetteListe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ajoutAlimentListe.setBackground(new java.awt.Color(153, 204, 255));

        titreAjoutAlimentListe.setText("Ajouter un aliment:");

        suprAlimentListeButton.setText("Supprimer");
        

        choixQuantiteeListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixQuantiteeListeActionPerformed(evt);
            }

			private void choixQuantiteeListeActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
        });

        ajoutAlimentListeButton.setText("Ajouter");
       

        titreAjoutQuantiteeListe.setText("Quantitée :");

        javax.swing.GroupLayout ajoutAlimentListeLayout = new javax.swing.GroupLayout(ajoutAlimentListe);
        ajoutAlimentListe.setLayout(ajoutAlimentListeLayout);
        ajoutAlimentListeLayout.setHorizontalGroup(
            ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutAlimentListeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ajoutAlimentListeLayout.createSequentialGroup()
                        .addComponent(titreAjoutQuantiteeListe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choixQuantiteeListe, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoutAlimentListeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titreAjoutAlimentListe)
                        .addGap(18, 18, 18)
                        .addComponent(choixAlimentListe, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutAlimentListeLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(ajoutAlimentListeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suprAlimentListeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        ajoutAlimentListeLayout.setVerticalGroup(
            ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutAlimentListeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixAlimentListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titreAjoutAlimentListe))
                .addGap(18, 18, 18)
                .addGroup(ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixQuantiteeListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titreAjoutQuantiteeListe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ajoutAlimentListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suprAlimentListeButton)
                    .addComponent(ajoutAlimentListeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imprimerListeButton.setText("imprimer");
        imprimerListeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerListeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pageMenuListeLayout = new javax.swing.GroupLayout(pageMenuListe);
        pageMenuListe.setLayout(pageMenuListeLayout);
        pageMenuListeLayout.setHorizontalGroup(
            pageMenuListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pageMenuListeLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(pageMenuListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pageMenuListeLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pageMenuListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajoutRecetteListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pageMenuListeLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(titreMenuListe)
                                .addGap(155, 155, 155)
                                .addComponent(imprimerListeButton))
                            .addComponent(ajoutAlimentListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82))
        );
        pageMenuListeLayout.setVerticalGroup(
            pageMenuListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pageMenuListeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pageMenuListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreMenuListe)
                    .addComponent(imprimerListeButton))
                .addGap(18, 18, 18)
                .addComponent(ajoutAlimentListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajoutRecetteListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageMenuListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pageMenuListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();   
    }

    public JButton getAjoutAlimentListeButton() {
		return ajoutAlimentListeButton;
	}

	public JButton getAjoutRecetteListeButton() {
		System.out.println("aa");
		return ajoutRecetteListeButton;
	}

	public JTextField getChoixAlimentListe() {
		return choixAlimentListe;
	}

	public JTextField getChoixRecetteListe() {
		return choixRecetteListe;
	}

	public JTable getTableListe() {
		return tableListe;
	}
	
	public JButton getSuprAlimentListeButton() {
		return suprAlimentListeButton;
	}

	public JTextField getChoixQuantiteeListe() {
		return choixQuantiteeListe;
	}
	
	public void setTableListeModel(DefaultTableModel tableListeModel) {
		
		this.tableListeModel = tableListeModel;
	}

	private void titreMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titreMenu3MouseClicked
        Main.controller.changerPage("accueil", null, null, null);
        this.dispose();
    }//GEN-LAST:event_titreMenu3MouseClicked

    private void StockButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockButton3MouseClicked
        //SUP
    }//GEN-LAST:event_StockButton3MouseClicked

    private void StockButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockButton3MouseEntered
        //SUP
    }//GEN-LAST:event_StockButton3MouseEntered

    private void StockButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockButton3ActionPerformed
        Main.controller.changerPage("menuStock", null, null, null);
        this.dispose();
    }//GEN-LAST:event_StockButton3ActionPerformed

    private void RecetteButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecetteButton3MouseClicked
        //SUP
    }//GEN-LAST:event_RecetteButton3MouseClicked

    private void RecetteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecetteButton3ActionPerformed
        Main.controller.changerPage("menuRecette", null, null, null);
        this.dispose();
    }

    private void ListButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListButton3MouseClicked
        //SUP
    }

    private void ListButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButton3ActionPerformed
        Main.controller.changerPage("menuListe", null, null, null);
        this.dispose();
    }

    private void ajoutRecetteListeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutRecetteListeButtonActionPerformed
      Main.controller.ajouterRecette(choixRecetteListe.getText());
    }



    private void imprimerListeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerListeButtonActionPerformed
    	Main.controller.ModifierListeFichier();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        	
            public void run() {
            	System.out.println("zaz");
               /* new MenuListe().setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListButton3;
    private javax.swing.JButton RecetteButton3;
    private javax.swing.JButton StockButton3;
    private javax.swing.JPanel ajoutAlimentListe;
    private javax.swing.JButton ajoutAlimentListeButton;
    private javax.swing.JPanel ajoutRecetteListe;
    private javax.swing.JButton ajoutRecetteListeButton;
    private javax.swing.JTextField choixAlimentListe;
    private javax.swing.JTextField choixRecetteListe;
    private javax.swing.JButton imprimerListeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel pageMenuListe;
    private javax.swing.JTable tableListe;
    private javax.swing.JLabel titreAjoutAlimentListe;
    private javax.swing.JLabel titreAjoutRecetteListe;
    private javax.swing.JLabel titreMenu3;
    private javax.swing.JLabel titreMenuListe;
    // End of variables declaration//GEN-END:variables


	public DefaultTableModel getTableListeModel() {
		return tableListeModel;
	}
}
